spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_connect
    username: root
    password: clean-code
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc: time_zone = EST